municipio:
    path:     /
    defaults: { _controller: "GeneralBundle:Municipio:index" }

municipio_show:
    path:     /{id}/show
    defaults: { _controller: "GeneralBundle:Municipio:show" }

municipio_new:
    path:     /new
    defaults: { _controller: "GeneralBundle:Municipio:new" }

municipio_create:
    path:     /create
    defaults: { _controller: "GeneralBundle:Municipio:create" }
    methods:  POST

municipio_edit:
    path:     /{id}/edit
    defaults: { _controller: "GeneralBundle:Municipio:edit" }

municipio_update:
    path:     /{id}/update
    defaults: { _controller: "GeneralBundle:Municipio:update" }
    methods:  [POST, PUT]

municipio_delete:
    path:     /{id}/delete
    defaults: { _controller: "GeneralBundle:Municipio:delete" }
    methods:  [POST, DELETE]
