regimentributario:
    path:     /
    defaults: { _controller: "GeneralBundle:RegimenTributario:index" }

regimentributario_show:
    path:     /{id}/show
    defaults: { _controller: "GeneralBundle:RegimenTributario:show" }

regimentributario_new:
    path:     /new
    defaults: { _controller: "GeneralBundle:RegimenTributario:new" }

regimentributario_create:
    path:     /create
    defaults: { _controller: "GeneralBundle:RegimenTributario:create" }
    methods:  POST

regimentributario_edit:
    path:     /{id}/edit
    defaults: { _controller: "GeneralBundle:RegimenTributario:edit" }

regimentributario_update:
    path:     /{id}/update
    defaults: { _controller: "GeneralBundle:RegimenTributario:update" }
    methods:  [POST, PUT]

regimentributario_delete:
    path:     /{id}/delete
    defaults: { _controller: "GeneralBundle:RegimenTributario:delete" }
    methods:  [POST, DELETE]
