Facturas\FacturasBundle\Entity\Certificado:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        certificado:
            type: string
            length: '120'
        path:
            type: string
            length: '120'
    lifecycleCallbacks: {  }