Facturas\FacturasBundle\Entity\Cliente:
    type: entity
    table: null
    repositoryClass: Facturas\FacturasBundle\Entity\ClienteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
        rfc:
            type: string
            length: '15'
        telefono:
            type: string
            length: '15'
        alias:
            type: string
            length: '20'
        email:
            type: string
            length: 255
    manyToOne:
        regimenTributario:
            targetEntity: Facturas\GeneralBundle\Entity\RegimenTributario
            inversedBy: cliente
            joinColumn:
                name: regimenTributario_id
                referencedColumnName: id
    oneToMany:
        direccionCliente:
            targetEntity: Facturas\FacturasBundle\Entity\DireccionCliente
            mappedBy: Cliente
        contacto:
            targetEntity: Facturas\FacturasBundle\Entity\Contacto
            mappedBy: Cliente
    lifecycleCallbacks: {  }
