Usuario\UserBundle\Entity\User:
    type: entity
<<<<<<< HEAD
    table: usuario
=======
    table: null
>>>>>>> ed27cfc61bc2e420f7235fb05a5a26863b928b1b
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userName:
            type: string
            length: '120'
        password:
            type: string
            length: '125'
        salt:
            type: string
            length: '120'
        dateCreate:
            type: datetime
        dateUpdate:
            type: datetime
            nullable: true
        userCreate:
            type: integer
        userUpdate:
            type: integer
            nullable: true
    manyToOne:
        perfil:         
            targetEntity: Usuario\UserBundle\Entity\perfil
            cascade: ["persist"]
    manyToMany:
        rol_user:
            targetEntity: Usuario\UserBundle\Entity\role
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
