Facturas\GeneralBundle\Entity\RegimenFiscal:
    type: entity
    table: null
    repositoryClass: Facturas\GeneralBundle\Entity\RegimenFiscalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        regimenFiscal:
            type: string
            length: '50'
    oneToMany:
        emisor:
            targetEntity: Facturas\FacturasBundle\Entity\Emisor
            mappedBy: RegimenFiscal
    lifecycleCallbacks: {  }
