<?php

namespace Facturas\GeneralBundle\Entity;

/**
 * ContribuyenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContribuyenteRepository extends \Doctrine\ORM\EntityRepository
{
}
