<?php

namespace Facturas\GeneralBundle\Entity;

/**
 * RegimenFiscalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimenFiscalRepository extends \Doctrine\ORM\EntityRepository
{
}
