<?php

namespace Facturas\FacturasBundle\Entity;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function clientes()
	{
		return $this->getEntityManager()->createQuery('SELECT c, dc FROM FacturasBundle:DireccionCliente dc LEFT JOIN dc.cliente c WHERE c.id = dc.cliente')->getResult();
	}

	public function clienteShow($id)
	{
		return $this->getEntityManager()->createQuery('SELECT c, dc FROM FacturasBundle:DireccionCliente dc JOIN dc.cliente c WHERE c.id = :id')->setParameter('id',$id)->getResult();
	}
}
