<?php

namespace Facturas\FacturasBundle\Entity;
/**
 * DireccionClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
