<?php

namespace Facturas\FacturasBundle\Entity;

/**
 * DireccionEmisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionEmisorRepository extends \Doctrine\ORM\EntityRepository
{
}
