<?php

namespace Facturas\FacturasBundle\Entity;

/**
 * EmisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmisorRepository extends \Doctrine\ORM\EntityRepository
{
	public function emisor($id)
	{
		return $this->getEntityManager()-> createQuery('SELECT e, de FROM FacturasBundle:DireccionEmisor de JOIN de.emisor e WHERE e.id = :id')->setParameter('id',$id)->getResult();
	}
}
