<?php

namespace Facturas\FacturasBundle\Entity;

/**
 * EmisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmisorRepository extends \Doctrine\ORM\EntityRepository
{
}
