<?php

namespace Facturas\FacturasBundle\Entity;

/**
 * FolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolioRepository extends \Doctrine\ORM\EntityRepository
{
}
